
//    AUTHENTICATE     //
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';
export const USER_AUTH_FAIL = 'USER_AUTH_FAIL';
export const USER_AUTH_LOAD = 'USER_AUTH_LOAD';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_SIGNOUT = 'USER_SIGNOUT';
export const SET_USER_STATUS = 'SET_USER_STATUS';

//    RESTAURANTS   //
export const REST_FETCH_SUCCESS = 'REST_FETCH_SUCCESS';
export const REST_FETCH_FAIL = 'REST_FETCH_FAIL';
export const REST_FETCH_LOADING = 'REST_FETCH_LOADING';
export const ALL_REST_FETCH_SUCCESS = 'ALL_REST_FETCH_SUCCESS';
export const CHEF_FETCH_SUCCESS = 'CHEF_FETCH_SUCCESS';
export const CHEF_FETCH_FAIL = 'CHEF_FETCH_FAIL';
export const CHEF_FETCH_LOADING = 'CHEF_FETCH_LOADING';
export const SET_ACTIVE_CHEF = 'SET_ACTIVE_CHEF';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

//    MENU    //
export const COMBO_FETCH_SUCCESS = 'MENU_FETCH_SUCCESS';
export const COMBO_FETCH_FAIL = 'MENU_FETCH_FAIL';
export const COMBO_FETCH_LOADING = 'MENU_FETCH_LOADING';
export const ITEM_FETCH_SUCCESS = 'ITEM_FETCH_SUCCESS';
export const ITEM_FETCH_FAIL = 'ITEM_FETCH_FAIL';
export const ITEM_FETCH_LOADING = 'ITEM_FETCH_LOADING';

//    MANAGER FUNCTIONS    //
export const MANAGER_FETCH_CHEF = 'MANAGER_FETCH_CHEF';
export const MANAGER_FETCH_DELIVERY = 'MANAGER_FETCH_DELIVERY';
export const MANAGER_FETCH_APPROVAL = 'MANAGER_FETCH_APPROVAL';
export const MANAGER_FETCH_FAIL = 'MANAGER_FETCH_FAIL';
export const MANAGER_REMOVE_WARNING = 'MANAGER_REMOVE_WARNING';
export const MANAGER_SUBMIT_APPROVAL = 'MANAGER_SUBMIT_APPROVAL';
