
//    AUTHENTICATE     //
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';
export const USER_AUTH_FAIL = 'USER_AUTH_FAIL';
export const USER_AUTH_LOAD = 'USER_AUTH_LOAD';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_SIGNOUT = 'USER_SIGNOUT';
export const SET_USER_STATUS = 'SET_USER_STATUS';

//    RESTAURANTS   //
export const REST_FETCH_SUCCESS = 'REST_FETCH_SUCCESS';
export const REST_FETCH_FAIL = 'REST_FETCH_FAIL';
export const REST_FETCH_LOADING = 'REST_FETCH_LOADING';
export const ALL_REST_FETCH_SUCCESS = 'ALL_REST_FETCH_SUCCESS';
export const CHEF_FETCH_SUCCESS = 'CHEF_FETCH_SUCCESS';
export const CHEF_FETCH_FAIL = 'CHEF_FETCH_FAIL';
export const CHEF_FETCH_LOADING = 'CHEF_FETCH_LOADING';
export const SET_ACTIVE_CHEF = 'SET_ACTIVE_CHEF';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

//    MENU    //
export const COMBO_FETCH_SUCCESS = 'MENU_FETCH_SUCCESS';
export const COMBO_FETCH_FAIL = 'MENU_FETCH_FAIL';
export const COMBO_FETCH_LOADING = 'MENU_FETCH_LOADING';
export const ITEM_FETCH_SUCCESS = 'ITEM_FETCH_SUCCESS';
export const ITEM_FETCH_FAIL = 'ITEM_FETCH_FAIL';
export const ITEM_FETCH_LOADING = 'ITEM_FETCH_LOADING';

//    ORDER UPDATE    //
export const ORDER_ADD_SUCCESS = 'ORDER_ADD_SUCCESS';
export const ORDER_ADD_FAIL = 'ORDER_ADD_FAIL';
export const ORDER_ADD_LOAD = 'ORDER_ADD_LOAD';
export const ITEM_ADD_SUCCESS = 'ITEM_ADD_SUCCESS';
export const ITEM_ADD_FAIL = 'ITEM_ADD_FAIL';
export const ITEM_ADD_LOAD = 'ITEM_ADD_LOAD';
