# Generated by Django 2.0.3 on 2018-03-25 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='chef',
            fields=[
                ('chef_id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_name', models.CharField(max_length=10)),
                ('warning', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='complaints',
            fields=[
                ('comp_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint_text', models.CharField(max_length=1000)),
                ('approval', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='compliments',
            fields=[
                ('comp_id', models.AutoField(primary_key=True, serialize=False)),
                ('compliment_text', models.CharField(max_length=1000)),
                ('approval', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('user_id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=25)),
                ('user_fname', models.CharField(max_length=25)),
                ('user_lname', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=5)),
                ('zipcode', models.CharField(max_length=5)),
                ('phone', models.CharField(max_length=10)),
                ('birthday', models.DateField()),
                ('memb_since', models.DateTimeField()),
                ('wallet', models.DecimalField(decimal_places=2, max_digits=5)),
                ('VIP', models.BooleanField()),
                ('warning', models.IntegerField()),
                ('order_count', models.IntegerField()),
                ('num_complaints', models.IntegerField()),
                ('last_order', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='customer_review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('pizza_rating', models.IntegerField()),
                ('store_rating', models.IntegerField()),
                ('delivery_rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='delivery',
            fields=[
                ('deliver_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField()),
                ('warning', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='delivery_review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_rating', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='employees',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=25)),
                ('emp_fname', models.CharField(max_length=25)),
                ('emp_lname', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=5)),
                ('zipcode', models.CharField(max_length=5)),
                ('phone', models.CharField(max_length=10)),
                ('ssn', models.CharField(max_length=9)),
                ('birthday', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_hired', models.DateTimeField()),
                ('num_compliment', models.IntegerField()),
                ('num_complaint', models.IntegerField()),
                ('last_order', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='menu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('picture', models.CharField(max_length=1000)),
                ('chef_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.chef')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.IntegerField()),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.menu')),
            ],
        ),
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('rest_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=5)),
                ('zipcode', models.CharField(max_length=5)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='rest_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.restaurant'),
        ),
        migrations.AddField(
            model_name='delivery_review',
            name='emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.employees'),
        ),
        migrations.AddField(
            model_name='delivery_review',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.customer'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.employees'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.restaurant'),
        ),
        migrations.AddField(
            model_name='customer_review',
            name='emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.employees'),
        ),
        migrations.AddField(
            model_name='customer_review',
            name='order_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.order'),
        ),
        migrations.AddField(
            model_name='customer_review',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.customer'),
        ),
        migrations.AddField(
            model_name='compliments',
            name='emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.employees'),
        ),
        migrations.AddField(
            model_name='compliments',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.customer'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.employees'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.customer'),
        ),
        migrations.AddField(
            model_name='chef',
            name='emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.employees'),
        ),
        migrations.AddField(
            model_name='chef',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.restaurant'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.customer'),
        ),
    ]
