# Generated by Django 2.0.3 on 2018-04-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
        migrations.AddField(
            model_name='employees',
            name='email',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
    ]
