# Generated by Django 2.0.3 on 2018-04-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_auto_20180403_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='last_order',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='memb_since',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='num_complaints',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='order_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='warning',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='date_hired',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='last_order',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='num_complaint',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='num_compliment',
            field=models.IntegerField(null=True),
        ),
    ]
