# Generated by Django 2.0.3 on 2018-04-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_auto_20180404_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='wallet',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
