# Generated by Django 2.0.3 on 2018-04-04 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_auto_20180404_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='VIP',
            field=models.BooleanField(default='DEFAULT VALUE'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
