# Generated by Django 2.0.3 on 2018-04-04 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_auto_20180404_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='VIP',
            field=models.IntegerField(null=True),
        ),
    ]
