# Generated by Django 2.0.3 on 2018-04-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_auto_20180404_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='user_id',
            field=models.CharField(max_length=60),
        ),
    ]
