# Generated by Django 2.0.3 on 2018-04-04 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0010_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='type',
            new_name='types',
        ),
    ]
