# Generated by Django 2.0.3 on 2018-04-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0011_auto_20180404_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employees',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
