# Generated by Django 2.0.3 on 2018-04-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0013_auto_20180404_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='user_id',
            new_name='emp_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='id',
        ),
        migrations.RemoveField(
            model_name='chef',
            name='id',
        ),
        migrations.RemoveField(
            model_name='complaints',
            name='id',
        ),
        migrations.RemoveField(
            model_name='compliments',
            name='id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='customer_review',
            name='id',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='id',
        ),
        migrations.RemoveField(
            model_name='delivery_review',
            name='id',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='id',
        ),
        migrations.AddField(
            model_name='account',
            name='acc_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='checkout_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chef',
            name='chef_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaints',
            name='complaint_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compliments',
            name='compliments_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='user_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer_review',
            name='review_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='deli_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery_review',
            name='review_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rest_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
