# Generated by Django 2.0.3 on 2018-04-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0014_auto_20180404_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='picture',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
