# Generated by Django 2.0.3 on 2018-04-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0015_auto_20180404_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('access_id', models.AutoField(primary_key=True, serialize=False)),
                ('access_code', models.CharField(max_length=64)),
                ('types', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='employees',
            name='password',
            field=models.CharField(max_length=64),
        ),
    ]
