# Generated by Django 2.0.3 on 2018-04-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0016_auto_20180404_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='warning',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='warning',
            field=models.IntegerField(null=True),
        ),
    ]
