# Generated by Django 2.0.3 on 2018-04-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0017_auto_20180404_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='menu_name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
