# Generated by Django 2.0.3 on 2018-04-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0019_auto_20180405_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='logo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
