# Generated by Django 2.0.3 on 2018-04-27 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0035_auto_20180425_2156'),
        ('tables', '0032_auto_20180423_2245'),
    ]

    operations = [
    ]
