# Generated by Django 2.0.3 on 2018-04-28 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0039_auto_20180428_1939'),
        ('tables', '0037_auto_20180427_1810'),
    ]

    operations = [
    ]
