# Generated by Django 2.0.3 on 2018-05-05 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0047_auto_20180502_1639'),
        ('tables', '0049_auto_20180502_2309'),
    ]

    operations = [
    ]
