# Generated by Django 2.0.3 on 2018-05-07 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0053_auto_20180505_2152'),
        ('tables', '0052_auto_20180507_2141'),
    ]

    operations = [
    ]
