# Generated by Django 2.0.3 on 2018-05-08 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0056_auto_20180508_1543'),
        ('tables', '0054_auto_20180508_0014'),
    ]

    operations = [
    ]
