# Generated by Django 2.0.3 on 2018-05-09 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0059_auto_20180509_1607'),
        ('tables', '0059_auto_20180509_1453'),
    ]

    operations = [
    ]
