# Generated by Django 2.0.3 on 2018-05-10 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0060_auto_20180510_1411'),
        ('tables', '0060_merge_20180509_2027'),
    ]

    operations = [
    ]
