# Generated by Django 2.0.3 on 2018-05-11 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0062_auto_20180510_2153'),
        ('tables', '0061_merge_20180510_1431'),
    ]

    operations = [
    ]
