# Generated by Django 2.0.3 on 2018-05-11 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0064_auto_20180511_0036'),
        ('tables', '0064_auto_20180511_1152'),
    ]

    operations = [
    ]
