# Generated by Django 2.0.3 on 2018-05-11 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0065_auto_20180511_1707'),
        ('tables', '0065_merge_20180511_1506'),
    ]

    operations = [
    ]
