# Generated by Django 2.0.3 on 2018-05-11 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0065_auto_20180511_1707'),
        ('tables', '0067_auto_20180511_1551'),
    ]

    operations = [
    ]
